# **Section A: Data Structures & Control Structures**

## Question 1: List Operations

In [ ]:
# Creating a list of 5 integers
numbers = [10, 20, 30, 40, 50]

print("Original List:", numbers)

# 1. append() → Adds one element at the end
numbers.append(60)
print("After append(60):", numbers)

# 2. extend() → Adds multiple elements
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# 3. insert() → Inserts element at specific position
numbers.insert(2, 25)
print("After insert(2, 25):", numbers)

# 4. remove() → Removes first matching value
numbers.remove(40)
print("After remove(40):", numbers)

# 5. pop() → Removes element by index (default last)
removed_item = numbers.pop()
print("After pop():", numbers)
print("Popped Item:", removed_item)

# 6. index() → Finds position of element
position = numbers.index(30)
print("Index of 30:", position)

# 7. count() → Counts occurrence of element
count_20 = numbers.count(20)
print("Count of 20:", count_20)

# 8. sort() → Sorts list in ascending order
numbers.sort()
print("After sort():", numbers)

# 9. reverse() → Reverses the list
numbers.reverse()
print("After reverse():", numbers)

# 10. clear() → Removes all elements
numbers.clear()
print("After clear():", numbers)

Original List: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70]
Popped Item: 80
Index of 30: 3
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]
After clear(): []


## Question 2: Tuple and Immutability


In [ ]:
# Creating a tuple with 3 student names
students = ("Kailash", "Riya", "Sonika")

print("Original Tuple:", students)

Original Tuple: ('Kailash', 'Riya', 'Sonika')


In [ ]:
# Trying to change the second name
students[1] = "Anjali"

TypeError: 'tuple' object does not support item assignment

The above code gives a **TypeError** because tuples are **immutable** in Python.

Once a tuple is created, its elements cannot be changed, added, or removed.

In [ ]:
print("Updated Tuple:", students)

Updated Tuple: ('Kailash', 'Riya', 'Sonika')


## Question 3: Set with Duplicate Values

In [ ]:
# Creating a set with duplicate values
numbers = {10, 20, 30, 20, 40, 10, 50}

# Printing the set
print("Set Output:", numbers)

Set Output: {50, 20, 40, 10, 30}


The duplicate values (10 and 20) are automatically removed because **sets** only store **unique elements**.

Also, the order of elements may be different because **sets** are **unordered** collections.

That is why the output contains only unique values and the sequence may change.

## Question 4: Dictionary Update and Add New Key

In [ ]:
# Creating the dictionary
student = {
    "name": "Kailash",
    "age": 18,
    "city": "Pune"
}

print("Original Dictionary:")
print(student)

# Updating the age
student["age"] = 23

# Adding a new key 'email'
student["email"] = "kailashsingh2203@gmail.com"

print("\nUpdated Dictionary:")
print(student)

Original Dictionary:
{'name': 'Kailash', 'age': 18, 'city': 'Pune'}

Updated Dictionary:
{'name': 'Kailash', 'age': 23, 'city': 'Pune', 'email': 'kailashsingh2203@gmail.com'}


## Question 5: Voting Eligibility Program

In [ ]:
age = int(input("Enter your age: "))

if age < 0:
    print("Invalid age entered.")
elif age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

Enter your age: -9
Invalid age entered.


## Question 6: Marks to Grade Program

In [ ]:
# User Input marks
marks = int(input("Enter marks: "))

# Grade calculation
if marks < 0 or marks > 100:
    print("Invalid marks entered.")
elif marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Enter marks: 50
Grade: C


## Question 7: Positive, Even, Zero, Negative Check

In [ ]:
# Taking user input number as a variable
num = int(input("Enter a number: "))

# First check if number is positive
if num > 0:
    print("The number is positive.")

    # Nested condition to check even or odd
    if num % 2 == 0:
        print("It is also an even number.")
    else:
        print("It is an odd number.")

# If not positive, check for zero or negative
elif num == 0:
    print("The number is zero.")

else:
    print("The number is negative.")

Enter a number: 0
The number is zero.


# **Section B: Numpy**

## Question 8: Scalar, 1D Array, and 2D Array

In [ ]:
import numpy as np

# 1. Scalar (0-D Array)
scalar = np.array(5)

# 2. 1D Array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])

# 3. 2D Array (2x3) with values from 10 to 60
array_2d = np.arange(10, 70, 10).reshape(2, 3)

print("Scalar:\n", scalar)
print("\n1D Array:\n", array_1d)
print("\n2D Array:\n", array_2d)

Scalar:
 5

1D Array:
 [1 2 3 4 5]

2D Array:
 [[10 20 30]
 [40 50 60]]


## Question 9: 4x4 Random Integer NumPy Array

In [ ]:
import numpy as np

# Generate 4x4 array of random integers
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Integer Array:")
print(random_array)

4x4 Random Integer Array:
[[82 19 77 56]
 [ 1 92  4 98]
 [90 25 84 48]
 [21 98 86 34]]


## Question 10: NumPy Array to Pandas DataFrame

In [ ]:
import numpy as np
import pandas as pd

# Creating a 3x3 NumPy array
array_2d = np.arange(10, 100, 10).reshape(3, 3)

print("NumPy Array:")
print(array_2d)

# Converting into Pandas DataFrame
df = pd.DataFrame(array_2d, columns=["A", "B", "C"])

print("\nPandas DataFrame:")
print(df)

NumPy Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Pandas DataFrame:
    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


## Question 11: Full Pandas DataFrame Operations

In [ ]:
import pandas as pd
import numpy as np

# Creating DataFrame manually
data = {
    "Name": ["Rahul", "Priya", "Aman", "Sneha", "Karan",
             "Riya", "Vikas", "Neha", "Aman", "Sneha"],

    "Age": [22, 24, 23, 25, 26,
            21, 27, 24, 23, 25],

    "City": ["Delhi", "Mumbai", "Pune", "Delhi", "Chennai",
             "Kolkata", "Mumbai", "Pune", "Pune", "Delhi"],

    "Salary": [50000, 60000, np.nan, 55000, 70000,
               48000, 65000, 62000, np.nan, 55000]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n")
print(df)

Original DataFrame:

    Name  Age     City   Salary
0  Rahul   22    Delhi  50000.0
1  Priya   24   Mumbai  60000.0
2   Aman   23     Pune      NaN
3  Sneha   25    Delhi  55000.0
4  Karan   26  Chennai  70000.0
5   Riya   21  Kolkata  48000.0
6  Vikas   27   Mumbai  65000.0
7   Neha   24     Pune  62000.0
8   Aman   23     Pune      NaN
9  Sneha   25    Delhi  55000.0


In [ ]:
print("DataFrame Info:\n")
print(df.info())

DataFrame Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None


In [ ]:
print("DataFrame Description:\n")
print(df.describe())

DataFrame Description:

             Age        Salary
count  10.000000      8.000000
mean   24.000000  58125.000000
std     1.825742   7510.706644
min    21.000000  48000.000000
25%    23.000000  53750.000000
50%    24.000000  57500.000000
75%    25.000000  62750.000000
max    27.000000  70000.000000


In [ ]:
print("Selected Columns (Name and City):\n")
print(df[["Name", "City"]])

Selected Columns (Name and City):

    Name     City
0  Rahul    Delhi
1  Priya   Mumbai
2   Aman     Pune
3  Sneha    Delhi
4  Karan  Chennai
5   Riya  Kolkata
6  Vikas   Mumbai
7   Neha     Pune
8   Aman     Pune
9  Sneha    Delhi


In [ ]:
df_no_city = df.drop("City", axis=1)

print("DataFrame After Dropping City Column:\n")
print(df_no_city)

DataFrame After Dropping City Column:

    Name  Age   Salary
0  Rahul   22  50000.0
1  Priya   24  60000.0
2   Aman   23      NaN
3  Sneha   25  55000.0
4  Karan   26  70000.0
5   Riya   21  48000.0
6  Vikas   27  65000.0
7   Neha   24  62000.0
8   Aman   23      NaN
9  Sneha   25  55000.0


In [ ]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

print("\nDataFrame After Filling Missing Salary:\n")
print(df)


DataFrame After Filling Missing Salary:

    Name  Age     City   Salary
0  Rahul   22    Delhi  50000.0
1  Priya   24   Mumbai  60000.0
2   Aman   23     Pune  58125.0
3  Sneha   25    Delhi  55000.0
4  Karan   26  Chennai  70000.0
5   Riya   21  Kolkata  48000.0
6  Vikas   27   Mumbai  65000.0
7   Neha   24     Pune  62000.0
8   Aman   23     Pune  58125.0
9  Sneha   25    Delhi  55000.0


In [ ]:
df = df.drop_duplicates().reset_index(drop=True)

print("\nDataFrame After Removing Duplicates:\n")
print(df)


DataFrame After Removing Duplicates:

    Name  Age     City   Salary
0  Rahul   22    Delhi  50000.0
1  Priya   24   Mumbai  60000.0
2   Aman   23     Pune  58125.0
3  Sneha   25    Delhi  55000.0
4  Karan   26  Chennai  70000.0
5   Riya   21  Kolkata  48000.0
6  Vikas   27   Mumbai  65000.0
7   Neha   24     Pune  62000.0
